format = """
$hostname\
$directory\

"""


right_format = """
$character\
$git_branch\
$git_commit\
$cmd_duration\
$shell\
"""

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[line_break]
disabled = true

[hostname]
ssh_only = true 
format = "[](fg:#24263A bg:none)[█](fg:#E8E3E3 bg:#24263A)[$ssh_symbol$hostname](bold bg:#E8E3E3)[](fg:#E8E3E3 bg:none) "
disabled = false

# Third param
[directory]
format = "[](fg:#24263A bg:none)[ ](fg:#6791c9 bg:#24263a)[](fg:#24263a bg:#24263A)[$path](fg:#E8E3E3 bg:#24263a)[ ](fg:#24263a bg:none)"
style = "fg:#E8E3E3 bg:#24263A bold"
truncation_length = 3
truncate_to_repo=false
read_only = " "

## SECOND LINE/ROW: Prompt
# Prompt: param 2 └─
[character]
success_symbol = "[](#6791c3 bold)"
error_symbol = "[](#B66467 bold)"


[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "
"portfolio" = " "

[cmd_duration]
min_time = 1
format = "[](fg:#24263a bg:none)[$duration]($style)[](fg:#24263a bg:none)"
disabled = false
style = "fg:#E8E3E3 bg:#24263a bold"


[git_branch]
format = "[](fg:#24263a bg:none)[$branch]($style)[](fg:#24263a bg:#24263a)[](fg:#24263a bg:#24263a)[](fg:#81C19B bg:#24263a)[](fg:#24263a bg:none) "
style = "fg:#E8E3E3 bg:#24263a"
symbol = " "

[git_status]
format="[](fg:#24263a bg:none)[$all_status$ahead_behind]($style)[](fg:#24263a bg:#24263a)[](fg:#24263a bg:#24263a)[ ](fg:#9ccfd8 bg:#24263a)[](fg:#24263a bg:none) "
style = "fg:#E8E3E3 bg:#24263a"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " 󰄸 "
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = " ${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

# # SYMBOLS

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

# [directory]

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true
